config/routes.rb
Rails.application.routes.draw do
 
  root :to => "invoice_headers#index"

  resources :invoice_lines
  resources :invoice_headers
  match 'invoice_lines/new/:invoice_header_id', to: 'invoice_lines#new', via: [:get]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/generate_pdf_module.rb
module GeneratePdfModule	

app/models/invoice_header.rb
class InvoiceHeader < ApplicationRecord
	has_many :invoice_lines, dependent: :destroy

	validates_presence_of :dni

	def get_fullname
  		[name, lastname].select(&:present?).join(' ').titleize
	end

	def get_numlines
		invoice_lines.count
	end

	def update_total
		self.total = invoice_lines.map{|i| i.line_total }.sum * 1.21
		self.tax = invoice_lines.map{|i| i.line_total }.sum * 0.21
		self.save
	end

end

app/models/invoice_line.rb
class InvoiceLine < ApplicationRecord
  belongs_to :invoice_header
  before_save  :set_line_total
  after_save :update_total

  
  def set_line_total
  	self.line_total = self.quantity * self.unit_price
  end

  def update_total
  	self.invoice_header.update_total  	
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invoice_headers_controller.rb
class InvoiceHeadersController < ApplicationController

	def new
	end

	def create
		@invoice = InvoiceHeader.create(params_invoice)
		redirect_to invoice_header_path(id: @invoice.id)
	end

	def edit
	end

	def update
		@invoice = InvoiceHeader.find(params[:id])
		@invoice.update(params_invoice)
		redirect_to invoice_header_path(id: @invoice.id)
	end

	def show
		@invoice = InvoiceHeader.find(params[:id])
		respond_to do |format|
	        format.html     
	        format.pdf do
	        	render template: 'invoice_headers/invoice_template.html.slim', pdf: 'invoice' + Time.now.strftime('%v %H:%M:%S').to_s, javascript_delay: 10000,
   				layout: 'pdf_layout.html.slim', disposition: (params[:mode])
	        end
	    end
    end
	

	def index
		@invoices = InvoiceHeader.all 
	end
	def destroy
	    @invoice = InvoiceHeader.find(params[:id])
	    @invoice.destroy
	    redirect_to invoice_headers_path()
	end


	private

		def params_invoice
			params.require(:invoice_header).permit(:id, :name, :lastname, :dni, :adress, :phone, :email)
		end


end

app/controllers/invoice_lines_controller.rb
class InvoiceLinesController < ApplicationController

	def new
	end

	def create		
		@in = InvoiceHeader.find(params[:invoice_line][:invoice_header_id])
		@line=@in.invoice_lines.create(params_line)
		@num_lin = @in.get_numlines
		redirect_to invoice_header_path(@in.id)
	end

	def destroy
	    @line = InvoiceLine.find(params[:id])
	    @invoice = @line.invoice_header
	    @line.destroy
	    @invoice.update_total
	    redirect_to invoice_header_path(@invoice.id)
	end

	private

		def params_line
			params.require(:invoice_line).permit(:invoice_header_id, :id, :name, :quantity, :unit_price, :color)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoice_headers/_form.html.slim
= form_for :invoice_header, url: invoice_headers_path do |f|
  .row
    .col-5.bg-dark.text-white.p-4
      .form-floating
        .col-sm
          label.col-form-label
            |  Nombre 
          = f.text_field :name, class: 'form-control' , id: 'floatingInputGrid', required: "true"
      .form-floating
        .col-sm
          label.col-form-label
            |  Apellido 
          = f.text_field :lastname, class: 'form-control' , required: "true"
      .form-floating
        .col-sm
          label.col-form-label
            |  DNI 
          = f.text_field :dni, class: 'form-control' , required: "true"
    .col-7.pt-4.pb-4.border.border-dark
      .form-floating
        .col-sm
          label.col-form-label
            |  Dirección 
          = f.text_field :adress, class: 'form-control' , required: "true"
      .form-floating
        .col-sm
          label.col-form-label
            |  Teléfono 
          = f.text_field :phone, class: 'form-control' , required: "true"
      .form-floating
        .col-sm
          label.col-form-label
            |  Correo Electrónico 
          = f.text_field :email, class: 'form-control' , required: "true"
    = f.hidden_field :total, value: 0.0
    br
    = f.hidden_field :tax, value: 0.0
    br
    .col-12.p-2.text-right
      = f.submit "Agregar", class: "col-2 btn btn-lg bg-dark text-white align-center mr-1"
      = link_to  invoice_headers_path(), class: "col-2 btn btn-lg bg-secondary text-white align-center" do 
          | Volver

app/views/invoice_headers/create.js.slim
- if @line.errors.empty?
  |  $('table tbody').append('
  = j render "row", item: @line, i: @num_lin
  | '); $('.alert-success').html("El producto ha sido creado con éxito").show(); $('#lines-modal').modal('hide'); 
- else
  |  alert('
  = @line.errors.full_messages[0]
  | '); 

app/views/invoice_headers/index.html.slim
.container-md
  .card.mt-5
    .card-header
      |  Listado Facturas 
    .card-body
      table.table
        thead.thead-dark
          tr
            th[scope="col"]
              | #
            th[scope="col"]
              | Nombre del Cliente
            th[scope="col"]
              
            th[scope="col"]
              | Fecha
            th.text-right[scope="col"]
              | Total
            th.text-right[scope="col"]
              | Taxes
        tbody
          - @invoices.each do |item, i|
            tr
              th[scope="row"]
                = i
              td
                = link_to invoice_header_path(id: item.id), title: 'Abrir Factura', class: "text-dark" do
                  = item.get_fullname
              td
                = link_to invoice_header_path(id: item.id, mode:'inline',format: :pdf), class: "btn btn-sm bg-light ml-1" do
                  i.fas.fa-file-pdf 
                = link_to invoice_header_path(id: item.id, mode:'attachment',format: :pdf), class: "btn btn-sm bg-light ml-1" do
                  i.fas.fa-file-download   
                = link_to invoice_header_path(id: item.id),method: :delete, class: "btn btn-sm bg-light" do
                  i.fas.fa-trash  
              td
                = item.created_at.strftime("%d-%m-%Y")
              td.text-right
                = number_to_currency(item.total, unit: '€',format: '%n%u')
              td.text-right
                = number_to_currency(item.tax, unit: '€',format: '%n%u')
    .card-footer.text-right
      = link_to new_invoice_header_path(), class: "btn btn-md bg-dark text-white" do
        |  Nueva Factura 

app/views/invoice_headers/invoice_template.html.slim
style
  |  .tabla-total { width: 95%; margin-left: 2em; margin-top: 2em; text-align: : center ; } .tbody, td { font-family: Arial, Helvetica, sans-serif; padding: 2em; text-align: center ; border: 0.15em solid #000099; } 
div[style="text-align: left;"]
  = image_tag wicked_pdf_asset_base64('zara.png'), width: '30%'
  address

  h3
    strong
      = @invoice.get_fullname
  h4
    | NIF 
    = @invoice.dni
  = @invoice.adress
  |  Teléfono 
  = @invoice.phone
  br
  |  E-mail 
  = @invoice.email
div[style="text-align: right; border-bottom: 0.15em solid "]
  div[style="font-size: 3em; margin-bottom: 1em;"]
    strong
      | FACTURA
  div[style="font-size: 1.5em;"]
    | Número  
    = @invoice.id
    br
    | Fecha   
    = @invoice.created_at.strftime("%d/%m/%Y")
div[style="text-align: right; border-bottom: 0.15em solid; margin-top: 1em;"]
  div[style="font-size: 2em;"]
    strong
      |  Total 
      =number_to_currency(@invoice.total, unit: '€',format: '%n%u')
  div[style="font-size: 1.5em;"]
    |  Taxes (IVA)  
    =number_to_currency(@invoice.tax, unit: '€',format: '%n%u')
table.tabla-total
  thead.bg-light[style=""]
    tr
      th[scope="col"]
        | #
      th[scope="col"]
        | Producto
      th.text-center[scope="col"]
        | Cantidad
      th.text-right[scope="col"]
        | Precio Unidad
      th.text-right[scope="col"]
        | Total
  tbody
    - @invoice.invoice_lines.each_with_index do |item, i|
      tr
        th[scope="row"]
          = i
        td
          strong
            = item.name
        td.text-center
          = item.quantity
        td.text-right
          = number_to_currency(item.unit_price, unit: '€',format: '%n%u')
        td.text-right
          = number_to_currency(item.line_total, unit: '€',format: '%n%u')

app/views/invoice_headers/new.html.slim
.col-6.container.mt-5
  .card
  	= image_tag 'zara.png', class: "col-3 btn btn-md p-3"
    .card-body.mt-0
      = render 'form'

app/views/invoice_headers/show.html.slim
.col-6.container.mt-5
  .card.p-0
    = image_tag 'zara.png', class: "col-3 btn btn-md p-3"
    .row.m-2.p-2
      .text-right
        = link_to invoice_header_path(id: @invoice.id),method: :delete, class: "col-1 btn btn-xs bg-light m-1" do
          i.fas.fa-trash
    .card-body.m-2
      .row
        .col-5.bg-dark.text-white.p-4
          .form-floating
            .col-sm
              h2
                | Factura # 
                = @invoice.id
          .form-floating
            .col-sm
              h3.col-form-label
                = @invoice.get_fullname
          .form-floating
            .col-sm
              label.col-form-label
                = @invoice.dni
        .col-7.pt-4.pb-4.border.border-dark
          .form-floating
            .col-sm
              label.col-form-label
                = @invoice.adress
          .form-floating
            .col-sm
              label.col-form-label
                = @invoice.phone
          .form-floating
            .col-sm
              label.col-form-label
                = @invoice.email
    .card-body.p-4
      .text-right.pd-2
        = link_to new_invoice_line_path(invoice_id: @invoice.id), remote: true ,class: "btn btn-xs" do
          i.fas.fa-plus
          |  Agregar Linea 
      table.table
        thead.bg-light
          tr
            th[scope="col"]
              | #
            th[scope="col"]
              | 
            th[scope="col"]
              | Producto
            th.text-center[scope="col"]
              | Cantidad
            th.text-right[scope="col"]
              | Precio Unidad
            th.text-right[scope="col"]
              | Total
        tbody
          - @invoice.invoice_lines.each_with_index do |item, i|
            tr
              th[scope="row"]
                = i
              th[scope="row"]
                = link_to invoice_line_path(id: item.id),method: :delete, class: "btn btn-sm bg-light" do
                  i.fas.fa-trash 
              td
                = item.name
              td.text-center
                = item.quantity
              td.text-right
                = number_to_currency(item.unit_price, unit: '€',format: '%n%u')
              td.text-right
                = number_to_currency(item.line_total, unit: '€',format: '%n%u')
      .row.bg-light.p-3.text-right
        p
          |  Tax(IVA):
          = number_to_currency(@invoice.tax, unit: '€',format: '%n%u') 
        h3
          |  Total (incluye IVA):
          = number_to_currency(@invoice.total, unit: '€',format: '%n%u')
      .row
        .text-right.p-2
          = link_to invoice_headers_path(), class: "col-2 btn btn-md bg-dark text-white" do
            |  Aceptar 

app/views/invoice_lines/_form.html.slim
#lines-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-label="Close"]
        span[aria-hidden="true"]
        | ×
        h4.modal-title
      .modal-body
        = form_for :invoice_line, url: invoice_lines_path(), remote: true do |f|
          = f.hidden_field :invoice_header_id, value: params[:invoice_id]
          .form-group
            = f.text_field :name, class: "form-control input-lg", placeholder: "Nombre del producto"
          .form-group
            = f.text_field :color, class: "form-control input-lg", placeholder: "Color"
          .form-group
            = f.number_field :unit_price, class: "form-control input-lg", placeholder: "Precio del producto"
          .form-group
            = f.number_field :quantity, class: "form-control input-lg", placeholder: "Cantidad"
    
          = f.submit "Agregar", class: "btn btn-md bg-light"

app/views/invoice_lines/_row.html.slim
tr
  th[scope="row"]
    = i
  td
    = item.name
  td.text-center
    = item.quantity
  td.text-right
    = number_to_currency(item.unit_price, unit: '€',format: '%n%u')
  td.text-right
    = number_to_currency(item.line_total, unit: '€',format: '%n%u')

app/views/invoice_lines/create.js.slim
- if @line.errors.empty?
  |  $('table tbody').append('
  = j render "row", item: @line, i: @num_lin
  | '); $('.alert-success').html("El producto ha sido creado con éxito").show(); $('#lines-modal').modal('hide'); 
- else
  |  alert('
  = @line.errors.full_messages[0]
  | '); 

app/views/invoice_lines/new.js.slim
|  $('
= j render "form", title: "Nueva linea"
| ').on('hidden.bs.modal', function (e) { $(this).remove(); $('.modal-backdrop').remove(); }).modal();

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App1
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"]
  body
    = yield

app/views/layouts/pdf_layout.html.slim
doctype html
html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    style
    = wicked_pdf_stylesheet_link_tag 'pdf'
    = wicked_pdf_javascript_include_tag 'number_pages'

  body[onload="number_pages"]
  	#header
  		
  	#content
    	= yield